### ISSUE TITLE
luajc error

### ISSUE THREAD

**Issue by mwhpeter** [taoguan/luaj#2]
Hello, some Lua scripts can run on luaj, but they give compilation errors when using luajc. Could you leave a contact, like your QQ number or email, so I can send you the scripts to take a look at? It’s the source code.

**Comment by taoguan** [comment]
Hello mwhpeter, you can paste your code on your comment or send it to my email - taohuan2512@163.com, thanks.

**Comment by mwhpeter** [comment]
> Hello mwhpeter, you can paste your code on your comment or send it to my email - taohuan2512@163.com, thanks.

I have already sent the code file to your email. Thank you!
